# Generated by Django 2.0 on 2018-05-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=50)),
                ('developer', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('short_desc', models.CharField(max_length=1000)),
                ('system_req', models.CharField(max_length=4000)),
                ('description', models.CharField(max_length=6000)),
                ('image', models.CharField(max_length=200)),
                ('genres', models.CharField(max_length=100)),
                ('similar_games', models.CharField(max_length=100)),
                ('base_price', models.CharField(max_length=20)),
                ('discount_ratio', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('sale_price', models.CharField(max_length=10)),
                ('lowest_price', models.CharField(max_length=20)),
                ('review_ratio', models.CharField(max_length=100)),
                ('windows', models.CharField(max_length=10)),
                ('mac', models.CharField(max_length=10)),
                ('linux', models.CharField(max_length=10)),
                ('discount', models.CharField(max_length=10)),
                ('specs', models.CharField(max_length=200)),
                ('metacritic', models.CharField(max_length=25)),
            ],
        ),
    ]
