# Generated by Django 2.0 on 2018-05-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='id',
        ),
        migrations.AlterField(
            model_name='games',
            name='game_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
