# Generated by Django 2.0 on 2018-05-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180519_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='order',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
