# Generated by Django 2.0 on 2018-05-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20180519_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_order',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
