# Generated by Django 2.0 on 2018-05-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20180519_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windows_stat', models.ImageField(upload_to='')),
                ('linux_stat', models.ImageField(upload_to='')),
                ('mac_stat', models.ImageField(upload_to='')),
                ('metacritic_stat', models.ImageField(upload_to='')),
                ('sale_stat', models.ImageField(upload_to='')),
            ],
        ),
    ]
